name: "Newman tests"
on: [push,pull_request]

jobs:
  build:
    runs-on: mac-os
    container:
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name:  Run API tests
        run: newman run RestfulBookerBVT.postman_collection.json -e Production.postman_environment.json
